-- =============================================================================
-- ResumAIner — Add generation reference data: adaptation_level, response_status
-- =============================================================================
-- Creates lookup tables and seed data for the generation pipeline.
-- adaptation_level: MINIMAL, BALANCED, MAXIMUM (ALL is request-level only)
-- =============================================================================

-- Adaptation level lookup table
CREATE TABLE IF NOT EXISTS adaptation_level (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20) NOT NULL,
    name        VARCHAR(50) NOT NULL,
    description TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_adaptation_level_code ON adaptation_level (code);

COMMENT ON TABLE  adaptation_level              IS 'Resume adaptation levels. ALL is a request-level selection only, not stored as a response level';
COMMENT ON COLUMN adaptation_level.code          IS 'Unique code: MINIMAL, BALANCED, MAXIMUM';
COMMENT ON COLUMN adaptation_level.name          IS 'Display name: Minimal, Balanced, Maximum';
COMMENT ON COLUMN adaptation_level.description   IS 'Optional description of the adaptation level';

-- Seed adaptation level data
INSERT INTO adaptation_level (code, name, description)
VALUES
    ('MINIMAL',  'Minimal',  'Light adaptation: preserves most original content'),
    ('BALANCED', 'Balanced', 'Balanced adaptation between original and optimized'),
    ('MAXIMUM',  'Maximum',  'Strong adaptation: heavily optimized for target vacancy')
ON CONFLICT (code) DO NOTHING;
