-- =============================================================================
-- ResumAIner — Create resume_generation_response and child section tables
-- =============================================================================
-- Stores AI-generated and user-edited response data per language and adaptation
-- level. One request produces N responses:
--   ENGLISH_ONLY + MINIMAL → 1 response
--   BILINGUAL + ALL       → 6 responses (EN/RU × MIN/BAL/MAX)
-- UUID PK per D7 hybrid strategy.
-- =============================================================================

-- =============================================================================
-- RESPONSE STATUS lookup table
-- =============================================================================
CREATE TABLE IF NOT EXISTS response_status (
    id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(20)  NOT NULL,
    name   VARCHAR(50)  NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_response_status_code ON response_status (code);

INSERT INTO response_status (code, name)
VALUES ('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')
ON CONFLICT (code) DO NOTHING;

-- =============================================================================
-- GENERATION RESPONSE
-- =============================================================================
CREATE TABLE resume_generation_response (
    id                      UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    generation_request_id   UUID            NOT NULL REFERENCES resume_generation_request(id),

    language_id             BIGINT          NOT NULL REFERENCES language(id),
    adaptation_level_id     BIGINT          NOT NULL REFERENCES adaptation_level(id),
    status_id               BIGINT          NOT NULL DEFAULT 1 REFERENCES response_status(id),

    -- Top-level fields (reviewed/edited by user)
    professional_title      VARCHAR(250)    NOT NULL,
    value_line              VARCHAR(500),
    professional_summary    TEXT            NOT NULL,
    professional_aspirations TEXT           NOT NULL,
    cover_letter            TEXT,

    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP,

    -- One response per language+adaptation combination per request
    CONSTRAINT uq_response_request_lang_adapt UNIQUE (generation_request_id, language_id, adaptation_level_id)
);

COMMENT ON TABLE  resume_generation_response              IS 'AI-generated response for one language + one adaptation level';
COMMENT ON COLUMN resume_generation_response.language_id  IS 'Actual language of this response: EN or RU';
COMMENT ON COLUMN resume_generation_response.adaptation_level_id IS 'Actual adaptation level: MINIMAL, BALANCED, or MAXIMUM';
COMMENT ON COLUMN resume_generation_response.status_id    IS 'DRAFT (AI returned) or FINALIZED (user approved)';
COMMENT ON COLUMN resume_generation_response.cover_letter IS 'Generated cover letter text, editable by user';

CREATE INDEX idx_response_request_id ON resume_generation_response (generation_request_id);

-- =============================================================================
-- RESPONSE WORK EXPERIENCE
-- =============================================================================
CREATE TABLE generation_response_experience (
    id              UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    response_id     UUID            NOT NULL REFERENCES resume_generation_response(id),

    job_title       VARCHAR(255)    NOT NULL,
    company_name    VARCHAR(255)    NOT NULL,
    description     TEXT            NOT NULL,
    location        VARCHAR(255)    NOT NULL,
    is_first_page   BOOLEAN         NOT NULL DEFAULT TRUE,
    start_date      DATE            NOT NULL,
    end_date        DATE,
    order_in_resume INTEGER         NOT NULL DEFAULT 0,

    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP
);

COMMENT ON TABLE  generation_response_experience              IS 'Generated work experience entry per response';
COMMENT ON COLUMN generation_response_experience.is_first_page IS 'TRUE = primary experience on page 1; FALSE = additional on page 2';
COMMENT ON COLUMN generation_response_experience.order_in_resume IS 'Fixed display order per DEC-030';

CREATE INDEX idx_resp_exp_response_id ON generation_response_experience (response_id);

-- =============================================================================
-- RESPONSE COURSE
-- =============================================================================
CREATE TABLE generation_response_course (
    id              UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    response_id     UUID            NOT NULL REFERENCES resume_generation_response(id),

    name            VARCHAR(255)    NOT NULL,
    provider        VARCHAR(255)    NOT NULL,
    is_first_page   BOOLEAN         NOT NULL DEFAULT TRUE,
    course_focus    VARCHAR(255),
    order_in_resume INTEGER         NOT NULL DEFAULT 0,

    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP
);

COMMENT ON TABLE  generation_response_course              IS 'Generated course/certificate entry per response';
COMMENT ON COLUMN generation_response_course.is_first_page IS 'TRUE = courses on page 1; FALSE = additional on page 2';

CREATE INDEX idx_resp_course_response_id ON generation_response_course (response_id);

-- =============================================================================
-- RESPONSE PROJECT
-- =============================================================================
CREATE TABLE generation_response_project (
    id              UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    response_id     UUID            NOT NULL REFERENCES resume_generation_response(id),

    project_name    VARCHAR(255)    NOT NULL,
    role            VARCHAR(255),
    description     TEXT            NOT NULL,
    location        VARCHAR(255),
    start_date      DATE            NOT NULL,
    end_date        DATE,
    order_in_resume INTEGER         NOT NULL DEFAULT 0,

    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP
);

CREATE INDEX idx_resp_proj_response_id ON generation_response_project (response_id);

-- =============================================================================
-- RESPONSE SKILL
-- =============================================================================
CREATE TABLE generation_response_skill (
    id              UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    response_id     UUID            NOT NULL REFERENCES resume_generation_response(id),

    skill_group     VARCHAR(255)    NOT NULL,
    skill_name      VARCHAR(255)    NOT NULL,
    order_in_resume INTEGER         NOT NULL DEFAULT 0,

    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP
);

CREATE INDEX idx_resp_skill_response_id ON generation_response_skill (response_id);

-- =============================================================================
-- RESPONSE PERSONAL INFORMATION
-- =============================================================================
CREATE TABLE generation_response_personal (
    id                              UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    response_id                     UUID            NOT NULL UNIQUE REFERENCES resume_generation_response(id),

    location                        VARCHAR(255)    NOT NULL,
    spoken_languages                VARCHAR(100)    NOT NULL,
    willingness_to_relocate         VARCHAR(50)     NOT NULL,
    willingness_for_business_trips  VARCHAR(50)     NOT NULL,
    citizenship                     VARCHAR(50)     NOT NULL,
    date_of_birth                   DATE            NOT NULL,
    work_formats                    VARCHAR(255),
    gpa_grade                       VARCHAR(20),
    order_in_resume                 INTEGER         NOT NULL DEFAULT 0,

    created_at                      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at                      TIMESTAMP
);

COMMENT ON TABLE  generation_response_personal IS 'Generated Personal Information per response language/adaptation — editable before final save';
