-- =============================================================================
-- ResumAIner — Create DB-backed resume budget configuration tables
-- =============================================================================
-- Replaces YAML-based external configuration (DEC-060, ERD v4.0).
-- Only one active config should exist. Budget config is read before generation
-- to determine content distribution rules (one-page vs two-page).
-- =============================================================================

-- =============================================================================
-- BUDGET CONFIGS — config identity and version metadata
-- =============================================================================
CREATE TABLE resume_budget_configs (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    version_no  INTEGER         NOT NULL DEFAULT 1,
    is_active   BOOLEAN         NOT NULL DEFAULT FALSE,
    description TEXT,
    created_at  TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP       NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  resume_budget_configs          IS 'Resume budget configuration — only one active config';
COMMENT ON COLUMN resume_budget_configs.is_active IS 'Only one config should be active; enforce via partial unique index';

CREATE UNIQUE INDEX uq_active_budget_config ON resume_budget_configs (is_active) WHERE is_active = TRUE;

-- =============================================================================
-- TEMPLATE SELECTION RULES — general scalar config values
-- =============================================================================
CREATE TABLE resume_template_selection_rules (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id       BIGINT          NOT NULL REFERENCES resume_budget_configs(id),
    rule_key        VARCHAR(100)    NOT NULL,
    value_type      VARCHAR(20)     NOT NULL CHECK (value_type IN ('int', 'boolean', 'text')),
    int_value       INTEGER,
    boolean_value   BOOLEAN,
    text_value      VARCHAR(255),
    description     TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE (config_id, rule_key)
);

-- =============================================================================
-- WORK EXPERIENCE DISTRIBUTION RULES — edge case distribution
-- =============================================================================
CREATE TABLE resume_work_experience_distribution_rules (
    id                          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id                   BIGINT          NOT NULL REFERENCES resume_budget_configs(id),
    case_key                    VARCHAR(20)     NOT NULL,
    min_total_jobs              INTEGER         NOT NULL,
    max_total_jobs              INTEGER         NOT NULL,
    min_projects                INTEGER         NOT NULL DEFAULT 0,
    max_projects                INTEGER,
    require_no_courses          BOOLEAN         NOT NULL DEFAULT FALSE,
    template_mode               VARCHAR(20)     NOT NULL CHECK (template_mode IN ('one_page', 'two_page')),
    page1_jobs                  INTEGER         NOT NULL,
    page2_jobs                  INTEGER         NOT NULL DEFAULT 0,
    page2_max_additional_jobs   INTEGER,
    priority                    INTEGER         NOT NULL DEFAULT 100,
    notes                       TEXT,
    created_at                  TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE (config_id, case_key)
);

-- =============================================================================
-- SECTION BUDGET RULES — min/max content metrics per section
-- =============================================================================
CREATE TABLE resume_section_budget_rules (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id       BIGINT          NOT NULL REFERENCES resume_budget_configs(id),
    section_key     VARCHAR(100)    NOT NULL,
    profile_key     VARCHAR(100)    NOT NULL,
    metric_key      VARCHAR(100)    NOT NULL,
    min_value       INTEGER,
    max_value       INTEGER,
    notes           TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE (config_id, section_key, profile_key, metric_key)
);
