-- =============================================================================
-- ResumAIner — Create AI usage log tables
-- =============================================================================
-- Tracks AI API calls per user and model (ERD v4.0). One API call may produce
-- one or two response rows (Bilingual). The junction table ai_usage_log_response
-- keeps monitoring in 3NF (DEC-063).
-- =============================================================================

CREATE TABLE ai_usage_log (
    id                      UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id                 UUID            NOT NULL REFERENCES users(id),
    ai_model_id             UUID            NOT NULL REFERENCES ai_model(id),
    generation_request_id   UUID            NOT NULL REFERENCES resume_generation_request(id),

    tokens_sent             INTEGER         NOT NULL DEFAULT 0,
    tokens_generated        INTEGER         NOT NULL DEFAULT 0,
    cost                    DECIMAL,

    created_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  ai_usage_log               IS 'One row per AI API call — tracks token usage';
COMMENT ON COLUMN ai_usage_log.tokens_sent    IS 'Prompt tokens sent to the AI provider';
COMMENT ON COLUMN ai_usage_log.tokens_generated IS 'Completion tokens generated by the AI provider';
COMMENT ON COLUMN ai_usage_log.cost           IS 'Post-MVP: cost per request';

CREATE INDEX idx_usage_log_user_id ON ai_usage_log (user_id);
CREATE INDEX idx_usage_log_request_id ON ai_usage_log (generation_request_id);

-- =============================================================================
-- USAGE LOG ↔ RESPONSE junction table
-- =============================================================================
-- One API call may create one or two response rows (Bilingual).
-- This junction avoids duplicating usage-log facts.
CREATE TABLE ai_usage_log_response (
    id                      UUID            DEFAULT gen_random_uuid() PRIMARY KEY,
    ai_usage_log_id         UUID            NOT NULL REFERENCES ai_usage_log(id),
    generation_response_id  UUID            NOT NULL REFERENCES resume_generation_response(id),

    UNIQUE (ai_usage_log_id, generation_response_id)
);

COMMENT ON TABLE ai_usage_log_response IS 'Links one AI API call to all generated response rows';
