-- =============================================================================
-- ResumAIner — Create PDF render configuration tables (Feature 008)
-- =============================================================================
-- Stores fit limits and page fill targets for the PDF generation pipeline.
-- Only one active config at a time (enforced via partial unique index).
-- Ported conceptually from spike V12.1 schema.sql.
-- =============================================================================

-- =============================================================================
-- PDF FIT LIMITS — bounds for the feedback fitting engine
-- =============================================================================
CREATE TABLE resume_pdf_fit_limits (
    id                          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key                  VARCHAR(100)    NOT NULL UNIQUE,
    active                      BOOLEAN         NOT NULL DEFAULT FALSE,
    body_font_min_px            NUMERIC(5,2)    NOT NULL,
    body_font_max_px            NUMERIC(5,2)    NOT NULL,
    line_height_min             NUMERIC(5,2)    NOT NULL,
    line_height_max             NUMERIC(5,2)    NOT NULL,
    section_gap_min_px          NUMERIC(5,2)    NOT NULL,
    section_gap_max_px          NUMERIC(5,2)    NOT NULL,
    item_gap_min_px             NUMERIC(5,2)    NOT NULL,
    item_gap_max_px             NUMERIC(5,2)    NOT NULL,
    paragraph_gap_min_px        NUMERIC(5,2)    NOT NULL,
    paragraph_gap_max_px        NUMERIC(5,2)    NOT NULL,
    bullet_gap_min_px           NUMERIC(5,2)    NOT NULL,
    bullet_gap_max_px           NUMERIC(5,2)    NOT NULL,
    max_attempts                INT             NOT NULL,
    page2_delta_limit_percent   NUMERIC(5,2)    NOT NULL,
    created_at                  TIMESTAMP       NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  resume_pdf_fit_limits                       IS 'PDF render fitting limits — only one active config at a time';
COMMENT ON COLUMN resume_pdf_fit_limits.config_key             IS 'Human-readable key, e.g. default-v1';
COMMENT ON COLUMN resume_pdf_fit_limits.page2_delta_limit_percent IS 'Max allowed divergence of page2 line-height and section-gap from page1 values, in percent';

CREATE UNIQUE INDEX uq_active_pdf_fit_limits ON resume_pdf_fit_limits (active) WHERE active = TRUE;

-- =============================================================================
-- PDF FILL TARGETS — minimum/maximum fill per page, language, and context
-- =============================================================================
CREATE TABLE resume_pdf_fill_targets (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fit_limits_id       BIGINT          NOT NULL REFERENCES resume_pdf_fit_limits(id),
    target_page_count   INT             NOT NULL,
    page_number         INT             NOT NULL,
    language_code       VARCHAR(10),
    project_count_min   INT,
    project_count_max   INT,
    min_fill            NUMERIC(5,4)    NOT NULL,
    max_fill            NUMERIC(5,4)    NOT NULL,
    priority            INT             NOT NULL DEFAULT 100,
    UNIQUE (fit_limits_id, target_page_count, page_number, language_code, project_count_min, project_count_max, priority)
);

COMMENT ON TABLE  resume_pdf_fill_targets                 IS 'Per-page fill targets for PDF validation';
COMMENT ON COLUMN resume_pdf_fill_targets.language_code    IS 'Optional language filter — NULL means applies to any language';
COMMENT ON COLUMN resume_pdf_fill_targets.project_count_min IS 'Inclusive lower bound for adaptive page2 min-fill rules';
COMMENT ON COLUMN resume_pdf_fill_targets.min_fill         IS 'Minimum fill ratio (0.0-1.0). Page must reach at least this fill percentage.';
COMMENT ON COLUMN resume_pdf_fill_targets.max_fill         IS 'Maximum fill ratio (0.0-1.0). Page must not exceed this fill percentage.';
