-- V5: Create users table (main entity)
-- UUID PK via gen_random_uuid() — entity tables use UUID for enumeration protection
-- FKs to lookup tables use BIGINT (matching BIGSERIAL PK of lookup tables)

CREATE TABLE users (
    id                    UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    email                 VARCHAR(255) NOT NULL,
    password_hash         VARCHAR(255) NOT NULL,
    username              VARCHAR(100),

    -- Lookup references (BIGINT matches BIGSERIAL PK of lookup tables)
    role_id               BIGINT       NOT NULL REFERENCES role(id),
    status_id             BIGINT       NOT NULL REFERENCES user_status(id),
    permission_id         BIGINT       NOT NULL REFERENCES user_permission(id),
    default_language_id   BIGINT       REFERENCES language(id),
    secondary_language_id BIGINT       REFERENCES language(id),

    is_privileged         BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Rate limiting
    failed_login_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP,

    -- Audit timestamps
    created_at            TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP    NOT NULL DEFAULT NOW(),
    deleted_at            TIMESTAMP,
    is_deleted            BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Unique constraint on email (case-insensitive, use lowercase for storage)
CREATE UNIQUE INDEX uq_users_email ON users (LOWER(email));

COMMENT ON TABLE  users                     IS 'Registered user accounts';
COMMENT ON COLUMN users.id                  IS 'UUID v4 primary key, generated by PostgreSQL';
COMMENT ON COLUMN users.email               IS 'User email, stored lowercase for unique constraint';
COMMENT ON COLUMN users.password_hash       IS 'BCrypt hash of the user password';
COMMENT ON COLUMN users.username            IS 'Optional display name';
COMMENT ON COLUMN users.role_id             IS 'FK to role table (USER/ADMIN)';
COMMENT ON COLUMN users.status_id           IS 'FK to user_status table (ACTIVE/BLOCKED)';
COMMENT ON COLUMN users.permission_id       IS 'FK to user_permission table (ALLOWED/FORBIDDEN)';
COMMENT ON COLUMN users.default_language_id IS 'FK to language table — preferred UI language';
COMMENT ON COLUMN users.failed_login_attempts IS 'Consecutive failed login counter for rate limiting';
COMMENT ON COLUMN users.locked_until        IS 'If set, account is locked until this timestamp';
COMMENT ON COLUMN users.created_at          IS 'Account creation timestamp';
COMMENT ON COLUMN users.updated_at          IS 'Last modification timestamp';
COMMENT ON COLUMN users.deleted_at          IS 'Soft-delete timestamp';
COMMENT ON COLUMN users.is_deleted          IS 'Soft-delete flag';
