-- V6: Create contact_detail table — one-to-one with users
-- UUID PK via gen_random_uuid() — entity tables use UUID
-- Created as empty shell on user registration, filled later in My Profile

CREATE TABLE contact_detail (
    id           UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id      UUID         NOT NULL UNIQUE REFERENCES users(id),

    -- All nullable — created empty, filled later
    full_name    VARCHAR(200),
    phone        VARCHAR(50),
    resume_email VARCHAR(255),
    location     VARCHAR(255),

    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  contact_detail      IS 'User profile contact information (one-to-one with users)';
COMMENT ON COLUMN contact_detail.id   IS 'UUID v4 primary key, generated by PostgreSQL';
COMMENT ON COLUMN contact_detail.user_id IS 'FK to users table — each user has exactly one contact_detail';
COMMENT ON COLUMN contact_detail.full_name IS 'User full name for resume';
COMMENT ON COLUMN contact_detail.phone IS 'User phone number';
COMMENT ON COLUMN contact_detail.resume_email IS 'Email displayed on resume (may differ from login email)';
COMMENT ON COLUMN contact_detail.location IS 'User location for resume';
