package com.resumainer.service;

import com.resumainer.dao.AiModelDao;
import com.resumainer.dao.GenerationRequestDao;
import com.resumainer.dao.PromptConfigDao;
import com.resumainer.dao.ResumeBudgetConfigDao.BudgetConfig;
import com.resumainer.model.AiModel;
import com.resumainer.model.ResumeGenerationRequest;
import com.resumainer.service.ai.AiClient;
import com.resumainer.service.ai.AiClientException;
import com.resumainer.service.ai.AiClientFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InOrder;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;

/**
 * Lifecycle tests for ResumeGenerationService.generate().
 * Focus on status guards: pending-only, processing-before-AI, completed-after-persist.
 */
@ExtendWith(MockitoExtension.class)
@org.mockito.junit.jupiter.MockitoSettings(strictness = org.mockito.quality.Strictness.LENIENT)
class ResumeGenerationServiceLifecycleTest {

    @Mock private GenerationRequestDao requestDao;
    @Mock private ResumePromptBuilder promptBuilder;
    @Mock private PromptConfigDao promptConfigDao;
    @Mock private AiClientFactory aiClientFactory;
    @Mock private AiResponseParser responseParser;
    @Mock private GenerationResponsePersistenceService persistenceService;
    @Mock private AiModelDao aiModelDao;
    @Mock private ResumeBudgetConfigService budgetConfigService;
    @Mock private AiClient aiClient;

    private ResumeGenerationService service;
    private final UUID requestId = UUID.randomUUID();
    private final UUID userId = UUID.randomUUID();
    private final UUID modelId = UUID.randomUUID();
    private final UUID promptConfigId = UUID.randomUUID();

    @BeforeEach
    void setUp() {
        service = new ResumeGenerationService(
                requestDao, promptBuilder, promptConfigDao, aiClientFactory, responseParser,
                persistenceService, aiModelDao, budgetConfigService);

        // Common stubs
        ResumePromptBuilder.PromptResult promptResult = new ResumePromptBuilder.PromptResult();
        promptResult.systemPrompt = "system";
        promptResult.requestPrompt = "request";
        promptResult.promptConfigId = promptConfigId;
        promptResult.profilePayloadJson = "{\"contact\":true}";
        promptResult.promptHash = "hash-123";
        when(promptBuilder.build(any(), any())).thenReturn(promptResult);
        when(promptConfigDao.insertPromptRenderLog(any(), any(), anyString(), anyString(), anyString(), anyString()))
                .thenReturn(UUID.randomUUID());
        when(aiClientFactory.createOpenRouter(any())).thenReturn(aiClient);
        when(aiClient.generate(anyString(), anyString())).thenReturn("{}");
        when(budgetConfigService.getActiveBudgetConfig())
                .thenReturn(new BudgetConfig(1L, "Test", 1));
        when(aiModelDao.findById(any())).thenReturn(new AiModel());
    }

    @Test
    void generateRejectsCompletedRequest() {
        // Given a completed request
        ResumeGenerationRequest request = new ResumeGenerationRequest();
        request.setId(requestId);
        request.setUserId(userId);
        request.setAiModelId(modelId);
        request.setStatus("completed");
        request.setLanguageMode("ENGLISH_ONLY");
        request.setAdaptationSelection("BALANCED");
        when(requestDao.findById(requestId, userId)).thenReturn(request);

        // When generate is called → status check rejects before any processing
        assertThrows(IllegalStateException.class, () ->
            service.generate(requestId, userId));

        // Then AI client is NOT called
        verify(aiClient, never()).generate(anyString(), anyString());
        // And no new response rows are created
        verify(persistenceService, never()).persistResponses(any(), any(), any());
        // And status was NOT changed to processing
        verify(requestDao, never()).updateStatus(requestId, userId, "processing", null, false);
    }

    @Test
    void generateRejectsProcessingRequest() {
        // Given a processing request (already being generated by another action)
        ResumeGenerationRequest request = new ResumeGenerationRequest();
        request.setId(requestId);
        request.setUserId(userId);
        request.setAiModelId(modelId);
        request.setStatus("processing");
        request.setLanguageMode("ENGLISH_ONLY");
        request.setAdaptationSelection("BALANCED");
        when(requestDao.findById(requestId, userId)).thenReturn(request);

        // When/Then — status check rejects before hasProcessingRequest or AI call
        assertThrows(IllegalStateException.class, () ->
            service.generate(requestId, userId));
        verify(aiClient, never()).generate(anyString(), anyString());
    }

    @Test
    void generateAcceptsPendingRequest() {
        // Given a pending request
        ResumeGenerationRequest request = new ResumeGenerationRequest();
        request.setId(requestId);
        request.setUserId(userId);
        request.setAiModelId(modelId);
        request.setStatus("pending");
        request.setLanguageMode("ENGLISH_ONLY");
        request.setAdaptationSelection("BALANCED");
        when(requestDao.findById(requestId, userId)).thenReturn(request);
        when(requestDao.hasProcessingRequest(userId)).thenReturn(false);

        // When
        assertDoesNotThrow(() -> service.generate(requestId, userId));

        // Then AI client was called
        verify(aiClient, atLeastOnce()).generate(anyString(), anyString());
    }

    @Test
    void generateSetsProcessingBeforeAiCall() {
        // Given a pending request
        ResumeGenerationRequest request = new ResumeGenerationRequest();
        request.setId(requestId);
        request.setUserId(userId);
        request.setAiModelId(modelId);
        request.setStatus("pending");
        request.setLanguageMode("ENGLISH_ONLY");
        request.setAdaptationSelection("BALANCED");
        when(requestDao.findById(requestId, userId)).thenReturn(request);
        when(requestDao.hasProcessingRequest(userId)).thenReturn(false);

        // When
        service.generate(requestId, userId);

        // Then request status was set to 'processing' before AI call
        // (verify that updateStatus was called with 'processing' before generate)
        verify(requestDao).updateStatus(requestId, userId, "processing", null, false);
    }

    @Test
    void failedRequestCanBeRetried() {
        // Given a failed request
        ResumeGenerationRequest request = new ResumeGenerationRequest();
        request.setId(requestId);
        request.setUserId(userId);
        request.setAiModelId(modelId);
        request.setStatus("failed");
        request.setLanguageMode("ENGLISH_ONLY");
        request.setAdaptationSelection("BALANCED");
        when(requestDao.findById(requestId, userId)).thenReturn(request);
        when(requestDao.hasProcessingRequest(userId)).thenReturn(false);

        // When/Then - a failed request can be retried (treated like pending)
        assertDoesNotThrow(() -> service.generate(requestId, userId));
        verify(aiClient, atLeastOnce()).generate(anyString(), anyString());
    }

    @Test
    void generateSavesPromptRenderLogBeforeAiCall() {
        // Given a pending request
        ResumeGenerationRequest request = new ResumeGenerationRequest();
        request.setId(requestId);
        request.setUserId(userId);
        request.setAiModelId(modelId);
        request.setStatus("pending");
        request.setLanguageMode("ENGLISH_ONLY");
        request.setAdaptationSelection("BALANCED");
        when(requestDao.findById(requestId, userId)).thenReturn(request);
        when(requestDao.hasProcessingRequest(userId)).thenReturn(false);

        // When
        service.generate(requestId, userId);

        // Then the final rendered prompt is saved before the AI call.
        InOrder inOrder = inOrder(promptBuilder, promptConfigDao, aiClient);
        inOrder.verify(promptBuilder).build(requestId, userId);
        inOrder.verify(promptConfigDao).insertPromptRenderLog(
                eq(requestId),
                eq(promptConfigId),
                eq("system"),
                eq("request"),
                eq("{\"contact\":true}"),
                eq("hash-123")
        );
        inOrder.verify(aiClient).generate("system", "request");
    }

}
